### PR TITLE
Show Single Month and Weekday Format support in Single Date Picker

### PR DESCRIPTION
**Pull request by vikalpgupta-birdeye**
Show Single Month and Weekday Format support in Single Date Picker

A solution to the issue mentioned here https://github.com/JSLancerTeam/react-google-flight-datepicker/issues/15

### CODE REVIEW

**Comment by vikalpgupta-birdeye** [comment]
@nhuthuy212507 @davidtran @Haroenv Can we please get this looked at and merged on priority, this is a useful feature to have

**Comment by Haroenv** [comment]
I don't work on this, sorry!

**Comment by davidtran** [comment]
@vikalpgupta-birdeye I am checking your pr

**Comment by davidtran** [comment]
@vikalpgupta-birdeye I have checked your PR. However, there are 2 issues when I add showSingleMonth prop:
- The layout of the single date picker doesn't fit mobile screen anymore
- The calendar animation is not smooth anymore, it was optimized for 2 months calendar layout so you need to work on it.

Screen Shot 2020-10-20 at 15 46 23

How to test:
- npm run dev
- Open SingleDatePicker.examples.md and add **showSingleMonth** to <SingleDatePicker />

Btw, I appreciate your PR. Just a few more works to make sure it is perfect and I will merge this PR.

**Comment by vikalpgupta-birdeye** [comment]
@davidtran Thanks for looking into the PR, I have resolved both of the above-mentioned issues, please do have a look and let me know if you need something else to be care of from my end. 

Also, I would like to connect with you separately on how you managed to find out the issue, as I currently don't see any unit test cases implemented with this project

**Comment by vikalpgupta-birdeye** [comment]
@davidtran Can you please look into this on priority, I have a project pending on this change, without this, I would have to involve patches in my code, thanks in advance

**Comment by davidtran** [comment]
I am pushing change now.

**Comment by davidtran** [comment]
@vikalpgupta-birdeye  I have published the version 0.17. I have renamed the props showSingleMonth to singleCalendar.

**Comment by vikalpgupta-birdeye** [comment]
> @vikalpgupta-birdeye I have published the version 0.17. I have renamed the props showSingleMonth to singleCalendar.

Works, Thanks for the quick turnaround :)

**Pull request merged**
